// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: v1/action.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Param struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to TestOneof:
	//
	//	*Param_ValueBytes
	//	*Param_ValueString
	//	*Param_ValueInt
	//	*Param_ValueFloat
	//	*Param_ValueStringArray
	TestOneof isParam_TestOneof `protobuf_oneof:"test_oneof"`
}

func (x *Param) Reset() {
	*x = Param{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_v1_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_v1_action_proto_rawDescGZIP(), []int{0}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Param) GetTestOneof() isParam_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (x *Param) GetValueBytes() []byte {
	if x, ok := x.GetTestOneof().(*Param_ValueBytes); ok {
		return x.ValueBytes
	}
	return nil
}

func (x *Param) GetValueString() string {
	if x, ok := x.GetTestOneof().(*Param_ValueString); ok {
		return x.ValueString
	}
	return ""
}

func (x *Param) GetValueInt() int64 {
	if x, ok := x.GetTestOneof().(*Param_ValueInt); ok {
		return x.ValueInt
	}
	return 0
}

func (x *Param) GetValueFloat() float64 {
	if x, ok := x.GetTestOneof().(*Param_ValueFloat); ok {
		return x.ValueFloat
	}
	return 0
}

func (x *Param) GetValueStringArray() string {
	if x, ok := x.GetTestOneof().(*Param_ValueStringArray); ok {
		return x.ValueStringArray
	}
	return ""
}

type isParam_TestOneof interface {
	isParam_TestOneof()
}

type Param_ValueBytes struct {
	ValueBytes []byte `protobuf:"bytes,2,opt,name=value_bytes,json=valueBytes,proto3,oneof"`
}

type Param_ValueString struct {
	ValueString string `protobuf:"bytes,3,opt,name=value_string,json=valueString,proto3,oneof"`
}

type Param_ValueInt struct {
	ValueInt int64 `protobuf:"varint,4,opt,name=value_int,json=valueInt,proto3,oneof"`
}

type Param_ValueFloat struct {
	ValueFloat float64 `protobuf:"fixed64,5,opt,name=value_float,json=valueFloat,proto3,oneof"`
}

type Param_ValueStringArray struct {
	ValueStringArray string `protobuf:"bytes,6,opt,name=value_string_array,json=valueStringArray,proto3,oneof"`
}

func (*Param_ValueBytes) isParam_TestOneof() {}

func (*Param_ValueString) isParam_TestOneof() {}

func (*Param_ValueInt) isParam_TestOneof() {}

func (*Param_ValueFloat) isParam_TestOneof() {}

func (*Param_ValueStringArray) isParam_TestOneof() {}

// Action which must be applied to source
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values []*Param `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_v1_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_v1_action_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetValues() []*Param {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_v1_action_proto protoreflect.FileDescriptor

var file_v1_action_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x31, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0xe3, 0x01, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x09, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00,
	0x52, 0x08, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x5f, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x00, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x2e, 0x0a,
	0x12, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x72,
	0x72, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x10, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x42, 0x0c, 0x0a,
	0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x3f, 0x0a, 0x06, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x26, 0x0a, 0x14,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x76, 0x31, 0x42, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x01, 0x5a, 0x04,
	0x2e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_action_proto_rawDescOnce sync.Once
	file_v1_action_proto_rawDescData = file_v1_action_proto_rawDesc
)

func file_v1_action_proto_rawDescGZIP() []byte {
	file_v1_action_proto_rawDescOnce.Do(func() {
		file_v1_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_action_proto_rawDescData)
	})
	return file_v1_action_proto_rawDescData
}

var file_v1_action_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_action_proto_goTypes = []interface{}{
	(*Param)(nil),  // 0: v1.Param
	(*Action)(nil), // 1: v1.Action
}
var file_v1_action_proto_depIdxs = []int32{
	0, // 0: v1.Action.values:type_name -> v1.Param
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_action_proto_init() }
func file_v1_action_proto_init() {
	if File_v1_action_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Param); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_action_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Param_ValueBytes)(nil),
		(*Param_ValueString)(nil),
		(*Param_ValueInt)(nil),
		(*Param_ValueFloat)(nil),
		(*Param_ValueStringArray)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_action_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_action_proto_goTypes,
		DependencyIndexes: file_v1_action_proto_depIdxs,
		MessageInfos:      file_v1_action_proto_msgTypes,
	}.Build()
	File_v1_action_proto = out.File
	file_v1_action_proto_rawDesc = nil
	file_v1_action_proto_goTypes = nil
	file_v1_action_proto_depIdxs = nil
}
