// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: v1/workflow.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkflowStep is a single action within a WorkflowJob.
type WorkflowStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uses     string `protobuf:"bytes,2,opt,name=uses,proto3" json:"uses,omitempty"`
	WithJson string `protobuf:"bytes,3,opt,name=with_json,json=withJson,proto3" json:"with_json,omitempty"` // JSON-encoded map[string]any
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowStep) GetUses() string {
	if x != nil {
		return x.Uses
	}
	return ""
}

func (x *WorkflowStep) GetWithJson() string {
	if x != nil {
		return x.WithJson
	}
	return ""
}

// WorkflowJob is a node in the processing DAG.
type WorkflowJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunsOn         string          `protobuf:"bytes,2,opt,name=runs_on,json=runsOn,proto3" json:"runs_on,omitempty"`
	Needs          []string        `protobuf:"bytes,3,rep,name=needs,proto3" json:"needs,omitempty"`
	TimeoutMinutes int32           `protobuf:"varint,4,opt,name=timeout_minutes,json=timeoutMinutes,proto3" json:"timeout_minutes,omitempty"`
	OnFailure      string          `protobuf:"bytes,5,opt,name=on_failure,json=onFailure,proto3" json:"on_failure,omitempty"`
	IfExpr         string          `protobuf:"bytes,6,opt,name=if_expr,json=ifExpr,proto3" json:"if_expr,omitempty"` // maps to "if" in YAML
	Steps          []*WorkflowStep `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *WorkflowJob) Reset() {
	*x = WorkflowJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowJob) ProtoMessage() {}

func (x *WorkflowJob) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowJob.ProtoReflect.Descriptor instead.
func (*WorkflowJob) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowJob) GetRunsOn() string {
	if x != nil {
		return x.RunsOn
	}
	return ""
}

func (x *WorkflowJob) GetNeeds() []string {
	if x != nil {
		return x.Needs
	}
	return nil
}

func (x *WorkflowJob) GetTimeoutMinutes() int32 {
	if x != nil {
		return x.TimeoutMinutes
	}
	return 0
}

func (x *WorkflowJob) GetOnFailure() string {
	if x != nil {
		return x.OnFailure
	}
	return ""
}

func (x *WorkflowJob) GetIfExpr() string {
	if x != nil {
		return x.IfExpr
	}
	return ""
}

func (x *WorkflowJob) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// WorkflowValidateCheck is a single validation check.
type WorkflowValidateCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uses     string `protobuf:"bytes,2,opt,name=uses,proto3" json:"uses,omitempty"`
	WithJson string `protobuf:"bytes,3,opt,name=with_json,json=withJson,proto3" json:"with_json,omitempty"`
}

func (x *WorkflowValidateCheck) Reset() {
	*x = WorkflowValidateCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workflow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowValidateCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowValidateCheck) ProtoMessage() {}

func (x *WorkflowValidateCheck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowValidateCheck.ProtoReflect.Descriptor instead.
func (*WorkflowValidateCheck) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowValidateCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowValidateCheck) GetUses() string {
	if x != nil {
		return x.Uses
	}
	return ""
}

func (x *WorkflowValidateCheck) GetWithJson() string {
	if x != nil {
		return x.WithJson
	}
	return ""
}

// WorkflowValidate defines pre-upload validation rules.
type WorkflowValidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxSize      string                   `protobuf:"bytes,1,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MinSize      string                   `protobuf:"bytes,2,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	ContentTypes []string                 `protobuf:"bytes,3,rep,name=content_types,json=contentTypes,proto3" json:"content_types,omitempty"`
	Checks       []*WorkflowValidateCheck `protobuf:"bytes,4,rep,name=checks,proto3" json:"checks,omitempty"`
}

func (x *WorkflowValidate) Reset() {
	*x = WorkflowValidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workflow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowValidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowValidate) ProtoMessage() {}

func (x *WorkflowValidate) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowValidate.ProtoReflect.Descriptor instead.
func (*WorkflowValidate) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowValidate) GetMaxSize() string {
	if x != nil {
		return x.MaxSize
	}
	return ""
}

func (x *WorkflowValidate) GetMinSize() string {
	if x != nil {
		return x.MinSize
	}
	return ""
}

func (x *WorkflowValidate) GetContentTypes() []string {
	if x != nil {
		return x.ContentTypes
	}
	return nil
}

func (x *WorkflowValidate) GetChecks() []*WorkflowValidateCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

// Workflow is the top-level v2 manifest.
type Workflow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      string            `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Name         string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description  string            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ContentTypes []string          `protobuf:"bytes,4,rep,name=content_types,json=contentTypes,proto3" json:"content_types,omitempty"`
	Tags         []string          `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	KeepOriginal bool              `protobuf:"varint,6,opt,name=keep_original,json=keepOriginal,proto3" json:"keep_original,omitempty"`
	OriginalName string            `protobuf:"bytes,7,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	Validate     *WorkflowValidate `protobuf:"bytes,8,opt,name=validate,proto3" json:"validate,omitempty"`
	Jobs         []*WorkflowJob    `protobuf:"bytes,9,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workflow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *Workflow) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetContentTypes() []string {
	if x != nil {
		return x.ContentTypes
	}
	return nil
}

func (x *Workflow) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Workflow) GetKeepOriginal() bool {
	if x != nil {
		return x.KeepOriginal
	}
	return false
}

func (x *Workflow) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *Workflow) GetValidate() *WorkflowValidate {
	if x != nil {
		return x.Validate
	}
	return nil
}

func (x *Workflow) GetJobs() []*WorkflowJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// DataWorkflow is the request body for SetWorkflow RPC.
type DataWorkflow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workflow *Workflow `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Group    string    `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *DataWorkflow) Reset() {
	*x = DataWorkflow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workflow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataWorkflow) ProtoMessage() {}

func (x *DataWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataWorkflow.ProtoReflect.Descriptor instead.
func (*DataWorkflow) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *DataWorkflow) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *DataWorkflow) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// WorkflowResponse is the response for GetWorkflow RPC.
type WorkflowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   ResponseStatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=v1.ResponseStatusCode" json:"status,omitempty"`
	Message  string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Workflow *Workflow          `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_workflow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workflow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowResponse) GetStatus() ResponseStatusCode {
	if x != nil {
		return x.Status
	}
	return ResponseStatusCode_UNKNOWN_INVALID
}

func (x *WorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

var File_v1_workflow_proto protoreflect.FileDescriptor

var file_v1_workflow_proto_rawDesc = []byte{
	0x0a, 0x11, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x0f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x53, 0x74, 0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x69, 0x74, 0x68, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0xd5, 0x01,
	0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x75, 0x6e, 0x73, 0x5f, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x75, 0x6e, 0x73, 0x4f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x0f,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x69,
	0x6e, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x5f, 0x66, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x6e, 0x46, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x45, 0x78, 0x70, 0x72, 0x12, 0x26, 0x0a,
	0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05,
	0x73, 0x74, 0x65, 0x70, 0x73, 0x22, 0x5c, 0x0a, 0x15, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x69, 0x74, 0x68, 0x4a,
	0x73, 0x6f, 0x6e, 0x22, 0xa0, 0x01, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x06,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x22, 0xb4, 0x02, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x6b, 0x65, 0x65, 0x70, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x6b, 0x65, 0x65, 0x70, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x08,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x4a, 0x6f, 0x62, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x22, 0x4e, 0x0a,
	0x0c, 0x44, 0x61, 0x74, 0x61, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x28, 0x0a,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x52, 0x08, 0x77,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x86, 0x01,
	0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x08,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x52, 0x08, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x42, 0x28, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70,
	0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x42, 0x08,
	0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_workflow_proto_rawDescOnce sync.Once
	file_v1_workflow_proto_rawDescData = file_v1_workflow_proto_rawDesc
)

func file_v1_workflow_proto_rawDescGZIP() []byte {
	file_v1_workflow_proto_rawDescOnce.Do(func() {
		file_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_workflow_proto_rawDescData)
	})
	return file_v1_workflow_proto_rawDescData
}

var file_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_workflow_proto_goTypes = []interface{}{
	(*WorkflowStep)(nil),          // 0: v1.WorkflowStep
	(*WorkflowJob)(nil),           // 1: v1.WorkflowJob
	(*WorkflowValidateCheck)(nil), // 2: v1.WorkflowValidateCheck
	(*WorkflowValidate)(nil),      // 3: v1.WorkflowValidate
	(*Workflow)(nil),              // 4: v1.Workflow
	(*DataWorkflow)(nil),          // 5: v1.DataWorkflow
	(*WorkflowResponse)(nil),      // 6: v1.WorkflowResponse
	(ResponseStatusCode)(0),       // 7: v1.ResponseStatusCode
}
var file_v1_workflow_proto_depIdxs = []int32{
	0, // 0: v1.WorkflowJob.steps:type_name -> v1.WorkflowStep
	2, // 1: v1.WorkflowValidate.checks:type_name -> v1.WorkflowValidateCheck
	3, // 2: v1.Workflow.validate:type_name -> v1.WorkflowValidate
	1, // 3: v1.Workflow.jobs:type_name -> v1.WorkflowJob
	4, // 4: v1.DataWorkflow.workflow:type_name -> v1.Workflow
	7, // 5: v1.WorkflowResponse.status:type_name -> v1.ResponseStatusCode
	4, // 6: v1.WorkflowResponse.workflow:type_name -> v1.Workflow
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_v1_workflow_proto_init() }
func file_v1_workflow_proto_init() {
	if File_v1_workflow_proto != nil {
		return
	}
	file_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_workflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workflow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowValidateCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workflow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowValidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workflow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workflow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workflow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataWorkflow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_workflow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_workflow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_workflow_proto_goTypes,
		DependencyIndexes: file_v1_workflow_proto_depIdxs,
		MessageInfos:      file_v1_workflow_proto_msgTypes,
	}.Build()
	File_v1_workflow_proto = out.File
	file_v1_workflow_proto_rawDesc = nil
	file_v1_workflow_proto_goTypes = nil
	file_v1_workflow_proto_depIdxs = nil
}
