services:
  # tracer:
  #   image: jaegertracing/all-in-one:latest
  #   ports: [ "16686:16686" ]

  s3server:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    volumes:
      - /tmp/data/minio/:/data

  redis:
    image: redis

  fileserver:
    image: halverneus/static-file-server:latest
    ports:
      - "8090:8080"
    environment:
      FOLDER: /web
      SHOW_LISTING: "true"
    volumes:
      - /tmp/data/minio/:/web

  nats:
    image: nats
    expose: [ "4222" ]

  server:
    image: github.com/apfs-io/apfs:latest
    ports:
      - "18080:8080"
      - "18082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 7s
      timeout: 2s
      retries: 5
    depends_on:
      redis:
        condition: service_started
      nats:
        condition: service_started
      fileserver:
        condition: service_started
      s3server:
        condition: service_started
    env_file:
      - ../../.env
    volumes:
      - /tmp/data/minio/:/tmp/data/storage

  test:
    image: github.com/apfs-io/apfs-testapp:latest
    depends_on:
      server:
        condition: service_healthy
    environment:
      STORAGE_CONNECT: dns://server:8081
